alias: Stopwatch Change
description: ''
trigger:
  - platform: state
    entity_id: input_select.select_cooking_timer
condition: []
action:
  - service: input_text.set_value
    data:
      value: '{{ states(''input_select.select_cooking_timer'') }}'
    target:
      entity_id: input_text.kitchen_display_entity_id
  - service: input_text.set_value
    data:
      value: >-
        {% if
        state_attr(states("input_select.select_cooking_timer"),"friendly_name")
        != None %}
          {{ state_attr(states("input_select.select_cooking_timer"),"friendly_name") }}
        {% else %}
          {{ "None" }}.
        {% endif %}
    target:
      entity_id: input_text.kitchen_display_friendly_name
  - service: input_text.set_value
    data:
      value: >-
        {% if state_attr(states("input_select.select_cooking_timer"),'duration')
        != None %}
          {{ state_attr(states("input_select.select_cooking_timer"),'duration') }}
        {% else %}
          {{ "None" }}.
        {% endif %}
    target:
      entity_id: input_text.kitchen_display_duration
  - service: input_text.set_value
    data:
      value: >-
        {% if state_attr(states("input_select.select_cooking_timer"),'icon') !=
        None %}
          {{ state_attr(states("input_select.select_cooking_timer"),'icon') }}
        {% else %}
          {{ "None" }}.
        {% endif %}
    target:
      entity_id: input_text.kitchen_display_icon
mode: restart